  // as per https://www.amctheatres.com/amc-scene/the-best-way-to-rewatch-the-mcu

  export default [{
          title: "Captain America: The First Avenger ",
          description: "CAPTAIN AMERICA: THE FIRST AVENGERis something of an extended introduction to the MCU. The bulk of the movie is set in the ’40s, and it introduces viewers to the SSR, which becomes S.H.I.E.L.D. Even the end-credits sequence, which features Nick Fury, is a nice setup for everything that will follow. Want to watch the Marvel movies in order? Start here.",
          image: "https://i1.wp.com/moviepilot.blog/wp-content/uploads/2018/04/Captain-America-The-First-Avenger.jpg?w=1200&ssl=1",
          yearOut: 2011,
      },
      {
          title: "Captain Marvel",
          description: "CAPTAIN MARVEL effectively takes the spot formerly held by IRON MAN as the proper kickoff for the entire MCU. The story is primarily set in the mid-’90s and features the first evolution of S.H.I.E.L.D. and an important stage of Nick Fury’s career. The story also sets up the Kree (later seen in GUARDIANS OF THE GALAXY) and, most importantly, deals with an object that becomes significant toward the end of Marvel’s Phase One. As the origin story for Carol Danvers (Brie Larson), this also feels more like a Phase One movie than anything Marvel has done in the past few years. In terms of tone and theme, it sits well in the beginning of the viewing order. Yes, there’s a connection to INFINITY WAR and ENDGAME, but just keep this film’s first post-credits sequence in your back pocket for later.",
          image: "https://i0.wp.com/moviepilot.blog/wp-content/uploads/2019/03/Captain-Marvel-Power-1.jpg?w=1400&ssl=1",
          yearOut: 2019,
      },
      {
          title: "Iron Man",
          description: "Although IRON MAN was the first MCU movie, it has more power when placed here. We know who Howard Stark is thanks to THE FIRST AVENGER. Watching his son take his first faltering steps into the “bigger universe” is an effective stage of the MCU movie order. The final scene, with Nick Fury stepping out of the shadows, will take on a subtly different meaning after the events of CAPTAIN MARVEL. Rather than hint at the birth of the MCU, it will become connective tissue linking the first three films together.",
          image: "https://i2.wp.com/moviepilot.blog/wp-content/uploads/2018/12/Iron-Man-2008.jpg?w=1280&ssl=1",
          yearOut: 2008,
      },
      {
          title: "Iron Man 2",
          description: "After IRON MAN introduces viewers to the modern-day iteration of S.H.I.E.L.D., the sequel dives deep into that organization. It also features Nick Fury in a far more significant role, allowing viewers to get a sense of just who this figure really is. Meanwhile, the focus on Howard Stark’s legacy continues to draw the narrative threads together. It makes perfect sense to watch IRON MAN 2at this point.",
          image: "https://i1.wp.com/moviepilot.blog/wp-content/uploads/2018/12/Iron-Man-2.jpg?w=750&ssl=1",
          yearOut: 2010,
      },
      {
          title: "The Incredible Hulk",
          description: "This particular adjustment to the viewing order is appropriate — while THE INCREDIBLE HULK actually happens at the same time as IRON MAN 2, the end-credits sequence assumes Stark now has a “consultant” role with S.H.I.E.L.D.",
          image: "https://i0.wp.com/moviepilot.blog/wp-content/uploads/2018/12/The-Incredible-Hulk-2008.jpg?w=1275&ssl=1",
          yearOut: 2008,
      },
      {
          title: "Thor",
          description: "THOR introduces viewers to Asgard and launches a series of stories inspired by events in the Realm Eternal. At the same time, it continues to develop the story of S.H.I.E.L.D., with Coulson and Hawkeye playing important roles.",
          image: "https://i1.wp.com/moviepilot.blog/wp-content/uploads/2018/12/Thor.jpg?w=1200&ssl=1",
          yearOut: 2011,
      },
      {
          title: "The Avengers",
          description: "This is a natural fit after the events of THOR, continuing many of that film’s themes and character arcs. Loki returns as a villain; the concept of the Tesseract is explored; and the existence of dangerous alien beings becomes public knowledge when the Chitauri invade New York. There’s also a more subtle detail as this is the first film to really hint that S.H.I.E.L.D. isn’t just “good guys.” THE AVENGERS includes a disturbing sequence in which the World Council orders a nuclear attack on American soil.",
          image: "https://i2.wp.com/moviepilot.blog/wp-content/uploads/2018/03/the-avengers-2012.jpg?w=1400&ssl=1",
          yearOut: 2012,
      },
      {
          title: "Thor: The Dark World ",
          description: "Here’s where the order of events really changes, but for good reason. The last two films have explored the cosmic side of the MCU, and it makes sense to continue that line. Some of the most important themes and ideas — particularly the relationship between Thor and Loki — follow on perfectly from THE AVENGERS. This also introduces the idea of the Infinity Stones, although they’re only partly explained at this point.",
          image: "https://i1.wp.com/moviepilot.blog/wp-content/uploads/2018/12/Thor-The-Dark-World.jpg?w=1000&ssl=1",
          yearOut: 2013,
      },
      {
          title: "Guardians of the Galaxy",
          description: "Continuing the cosmic focus, GUARDIANS OF THE GALAXY unveils another Infinity Stone. The Collector, introduced in the stinger of THOR: THE DARK WORLD, makes another appearance, tying the two films together. Viewers are left with a strong sense that the Infinity Stones are being brought into play across the universe.",
          image: "https://i1.wp.com/moviepilot.blog/wp-content/uploads/2018/12/Guardians-of-the-Galaxy.jpg?w=1200&ssl=1",
          yearOut: 2014,
      },
      {
          title: " Guardians of the Galaxy Vol. 2",
          description: "The events of GUARDIANS OF THE GALAXY VOL. 2 are set only a couple of months after the first film, so it makes sense for this to follow straight on. It continues the space-opera style and tone established by the last two films in our Marvel movie order.",
          image: "https://i2.wp.com/moviepilot.blog/wp-content/uploads/2018/03/guardians-of-the-galaxy-groot-sacrifice.jpg?w=1400&ssl=1",
          yearOut: 2017,
      },
      {
          title: "Iron Man 3",
          description: "The cosmic diversion is over, and the focus now moves back to Earth, where Tony Stark is dealing with the emotional fallout from THE AVENGERS. The passage of time between the films actually makes Tony’s PTSD feel more significant, while also more making it feel more natural that Stark has had the time to build so many armors.",
          image: "https://i0.wp.com/moviepilot.blog/wp-content/uploads/2018/12/Iron-Man-3.jpg?w=1200&ssl=1",
          yearOut: 2013,
      },
      {
          title: "Captain America: The Winter Soldier ",
          description: "Continuing with the Earthly focus, this movie shows what Captain America is up to. This story could even be happening at the same time as IRON MAN 3, explaining why Cap doesn’t help Tony against the Mandarin and why Stark isn’t on hand to deal with Hydra. Or maybe Cap and Stark are merely still wary of one another at this stage. Perhaps most importantly, placing this film here begins a Falcon arc that will run through the next few movies.",
          image: "https://i1.wp.com/moviepilot.blog/wp-content/uploads/2018/03/captain-america-winter-soldier.jpg?w=1400&ssl=1",
          yearOut: 2014,
      },
      {
          title: "Avengers: Age of Ultron",
          description: "This is another natural fit. The film opens with the Avengers taking down a major Hydra base. In thematic terms, placing this close to IRON MAN 3makes Tony’s emotional journey feel more immediate and natural. This film also begins to tie the Earth-bound adventures into the cosmic stories, with another Infinity Stone revealed. Thor’s vision establishes a sense of impending threat.",
          image: "https://i0.wp.com/moviepilot.blog/wp-content/uploads/2018/03/avengers-age-of-ultron.png?w=1044&ssl=1",
          yearOut: 2015,
      },
      {
          title: "Ant-Man",
          description: "Set in the immediate aftermath of AVENGERS: AGE OF ULTRON, ANT-MAN contains subtle references to the devastation at Sokovia. Placing it here in the lineup makes the Falcon fight carry additional weight, bringing Sam closer to primary character status.",
          image: "https://i1.wp.com/moviepilot.blog/wp-content/uploads/2018/04/antman.jpg?w=960&ssl=1",
          yearOut: 2015,
      },
      {
          title: "Captain America: Civil War",
          description: "The Sokovia arc that begun in AVENGERS: AGE OF ULTRON comes to a head in CAPTAIN AMERICA: CIVIL WAR, tearing the Avengers apart. CIVIL WAR acts as the launchpad for the next batch of Earth-bound stories, so they slot in nicely after it. It also follows on perfectly from ANT-MAN’s end-credits scene.",
          image: "https://i1.wp.com/moviepilot.blog/wp-content/uploads/2018/03/civil-war-airport-fight.jpg?w=1400&ssl=1",
          yearOut: 2016,
      },
      {
          title: "Black Panther",
          description: "Black Panther was introduced in CIVIL WAR, and this continues his story. It’s appropriate to drop this movie in next, as BLACK PANTHER is set only a week after the Avengers divide, and the Wakandan focus follows on nicely from the end-credits sequence.",
          image: "https://i1.wp.com/moviepilot.blog/wp-content/uploads/2018/01/black-panther-vs-erik-killmonger.jpg?w=1400&ssl=1",
          yearOut: 2018,
      },
      {
          title: "Spider-Man: Homecoming",
          description: "Set two months after CIVIL WAR, SPIDER-MAN: HOMECOMING focuses on Peter Parker. It’s important to note that Tony Stark has been given time to heal a little, so this viewing order makes sense.",
          image: "https://i2.wp.com/moviepilot.blog/wp-content/uploads/2018/04/Spider-Man-Iron-Man.jpg?w=1280&ssl=1",
          yearOut: 2017,
      },
      {
          title: "Doctor Strange",
          description: "Placing DOCTOR STRANGE here gives the film real importance as a thematic tie between the MCU’s Earth-bound and cosmic movies. DOCTOR STRANGE introduces the concept of magic and brings the Time Stone into play. The Quantum Realm also plays a subtle role, as Strange glimpses it while being sent careering through the dimensions. Finally, the end-credits scene leads nicely into THOR: RAGNAROK.",
          image: "https://i1.wp.com/moviepilot.blog/wp-content/uploads/2018/04/Doctor-Strange-Sanctum-Sanctorum.png?w=1400&ssl=1",
          yearOut: 2016,
      },
      {
          title: "Thor: Ragnarok",
          description: "This film follows on logically from DOCTOR STRANGE. (There’s even a cameo.) The end credits begin the direct buildup to AVENGERS: INFINITY WAR, with the Asgardian refugees intercepted in space by Thanos.",
          image: "https://i0.wp.com/moviepilot.blog/wp-content/uploads/2018/03/thor-ragnarok.jpg?w=1400&ssl=1",
          yearOut: 2017,
      },
      {
          title: "Ant-Man & the Wasp",
          description: "This is a difficult one to place in this thematic structure. While it returns to the Earth-bound adventures, ANT-MAN AND THE WASP is fantastical and funny. The bulk of the story is set before the events of AVENGERS: INFINITY WAR, so it makes sense to place it here. This particular viewing order does change how the post-credits scene plays, however. Rather than knowing what’s going on, you’re with the same sense of shock and horror felt by Hank Pym or Scott Lang.",
          image: "https://i2.wp.com/moviepilot.blog/wp-content/uploads/2018/04/Ant-Man-and-the-Wasp-.jpeg?w=1035&ssl=1",
          yearOut: 2018,
      },
      {
          title: " Avengers: Infinity War",
          description: "In this order, AVENGERS: INFINITY WAR will be the last thing you watch before AVENGERS: ENDGAME. That works particularly well when you consider that, according to screenwriters Christopher Markus and Stephen McFeely, the snap was originally in ENDGAME. These two films may not be a traditional Parts I and II anymore, but their relationship is so close that it’s better to watch them back to back — just how they were filmed.",
          image: "https://i2.wp.com/moviepilot.blog/wp-content/uploads/2018/05/Steve-Rogers-Infinity-War.jpg?w=1400&ssl=1",
          yearOut: 2018,
      },
      {
          title: "Avengers: Endgame",
          description: "It’s no surprise that ENDGAME is definitely the wrap-up to any MCU viewing party, at least for the time being. The world reels from the aftereffects of Thanos’s snap, and our heroes are just as affected as everyone else, if not more so. The fourth AVENGERS movie is very much the culmination of ten years of story — it is deeply tied to everything that came before, and particularly the first three AVENGERS movies. (That’s a hint about which movies you should definitely rewatch, if you only have time for a handful.) The story ties up a handful of plot threads that began in several previous movies, and opens up new dimensions for future MCU movies to explore.",
          image: "https://i2.wp.com/moviepilot.blog/wp-content/uploads/2018/12/Avengers-Endgame-Tony-in-Space.jpg?w=1440&ssl=1",
          yearOut: 2019,
      }
  ];